#!/usr/bin/env python3
"""Regenerate the Maki icon block in resources/viewer/src/index/136-poi-icons.js.

The viewer draws its POI icons from Maki (https://github.com/mapbox/maki,
CC0 1.0) at runtime: each icon is one SVG path on a 15x15 grid, which
136-poi-icons.js rasterizes with Path2D and hands to map.addImage(). The
paths live INSIDE index.html rather than as a sprite.png/.json in the ZIM
because published ZIMs are updated by in-place slot patching, which can
replace index.html but cannot add entries (docs/viewer-slots.md): inline
icons reach every shipped region with the next viewer patch, a sprite would
only reach rebuilt ones.

    python tools/maki/build_poi_icons.py            # rewrite the block
    python tools/maki/build_poi_icons.py --check    # exit 1 if it would change

Downloads the pinned npm tarball (URL + sha256 below) into the system temp
directory ($TMPDIR/streetzim-maki). Then run python tools/build_viewer.py.
"""
from __future__ import annotations

import argparse
import hashlib
import html
import io
import json
import re
import sys
import tarfile
import tempfile
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
PART = ROOT / "resources" / "viewer" / "src" / "index" / "136-poi-icons.js"
CACHE = Path(tempfile.gettempdir()) / "streetzim-maki"

MAKI_VERSION = "8.2.0"
MAKI_URL = f"https://registry.npmjs.org/@mapbox/maki/-/maki-{MAKI_VERSION}.tgz"
MAKI_SHA256 = "f6e59156521117c311c0e73a6aeef8d5039daea9c7fbe1ff9264e18a3ebec87f"

# Every icon _SZ_POI_ICON in 136-poi-icons.js can name. The test
# (tests/viewer_style_js.test.mjs) fails if the mapping names one not here.
ICONS = [
    "restaurant", "fast-food", "cafe", "bar", "beer", "ice-cream", "bakery",
    "grocery", "shop", "clothing-store", "alcohol-shop",
    "lodging", "campsite",
    "hospital", "doctor", "dentist", "pharmacy",
    "school", "college", "library",
    "museum", "art-gallery", "attraction", "viewpoint", "monument", "castle",
    "zoo", "aquarium", "theatre", "cinema", "music", "information", "picnic-site",
    "stadium", "swimming", "golf", "park", "garden", "playground",
    "bus", "rail", "rail-light", "rail-metro", "entrance", "airport", "fuel",
    "parking", "car", "bicycle", "harbor", "ferry",
    "bank", "post", "police", "fire-station", "town-hall",
    "place-of-worship", "religious-christian", "religious-jewish",
    "religious-muslim", "religious-buddhist",
    "toilet", "drinking-water", "cemetery", "laundry", "hairdresser",
]

BEGIN = "// BEGIN maki-icons"
END = "// END maki-icons"


def tarball() -> bytes:
    CACHE.mkdir(parents=True, exist_ok=True)
    path = CACHE / f"maki-{MAKI_VERSION}.tgz"
    if not path.exists():
        with urllib.request.urlopen(MAKI_URL, timeout=60) as r:
            path.write_bytes(r.read())
    data = path.read_bytes()
    got = hashlib.sha256(data).hexdigest()
    if got != MAKI_SHA256:
        raise SystemExit(f"{path}: sha256 {got} != pinned {MAKI_SHA256}")
    return data


def icon_paths(tgz: bytes) -> dict[str, str]:
    out: dict[str, str] = {}
    with tarfile.open(fileobj=io.BytesIO(tgz), mode="r:gz") as tf:
        for name in ICONS:
            member = tf.extractfile(f"package/icons/{name}.svg")
            if member is None:
                raise SystemExit(f"maki {MAKI_VERSION} has no icon {name!r}")
            svg = member.read().decode("utf-8")
            if 'viewBox="0 0 15 15"' not in svg:
                raise SystemExit(f"{name}: not on the 15x15 grid")
            if re.search(r"<(circle|rect|polygon|polyline|ellipse|line|g)\b|transform=", svg):
                raise SystemExit(f"{name}: has shapes other than one plain path")
            ds = re.findall(r'<path\b[^>]*\sd="([^"]+)"', svg)
            if len(ds) != 1:
                raise SystemExit(f"{name}: {len(ds)} paths, want exactly 1")
            out[name] = re.sub(r"\s+", " ", html.unescape(ds[0])).strip()
    return out


def block(paths: dict[str, str]) -> str:
    lines = [
        f"{BEGIN} (generated by tools/maki/build_poi_icons.py from Maki "
        f"{MAKI_VERSION}, CC0 1.0; do not edit)",
        "var _SZ_MAKI = {",
    ]
    items = list(paths.items())
    for i, (name, d) in enumerate(items):
        comma = "," if i < len(items) - 1 else ""
        lines.append(f"  {json.dumps(name)}: {json.dumps(d)}{comma}")
    lines.append("};")
    lines.append(END)
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=next(iter((__doc__ or "").splitlines()), ""))
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    src = PART.read_text(encoding="utf-8")
    a, b = src.find(BEGIN), src.find(END)
    if a < 0 or b < a:
        raise SystemExit(f"no {BEGIN} ... {END} block in {PART}")
    new = src[:a] + block(icon_paths(tarball())) + src[b + len(END):]
    if args.check:
        if new != src:
            print(f"{PART.relative_to(ROOT)} is stale; run {Path(__file__).name}", file=sys.stderr)
            return 1
        print("ok: maki block is current")
        return 0
    PART.write_text(new, encoding="utf-8")
    print(f"wrote {PART.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
