"""Overture release and schema helpers shared by download_overture_data.py
and the merges in streetzim/addresses.py.

Release: download_overture_data.py writes the release a parquet was cut
from into its key-value metadata (``overture_release``); the ops wrappers
also put it in the file name (``places-<id>-<release>.parquet``).

Places categories: Overture removed ``categories`` (``primary`` /
``alternate``) in release 2026-09-23.0. Its replacement ``taxonomy``
(``primary`` / ``hierarchy`` / ``alternates``) names the same leaf
categories, 607 of them spelled differently ("dentist" is now
"dental_clinic", "car_dealer" "auto_dealer", "accommodation" "lodging").
The search records' ``cat`` / ``s`` values, the chip rules
(cloud/chip_rules.py), the viewer's icons and labels, and the generic-bucket
refinement in merge_overture_places all use the old names, so
``taxonomy.primary`` is mapped back to them with TAXONOMY_TO_LEGACY.
``basic_category`` is coarser (e.g. "wellness_service" for "spas") and is
not used.

TAXONOMY_TO_LEGACY lists every taxonomy.primary that differs from
categories.primary in release 2026-08-19.0, which carries both columns:
over its 73.6 M places the pairing is one-to-one except for 4 rows, and
no old name is reused as a different new name. Values absent from the
table (unchanged names, and categories added after 2026-08-19.0) pass
through as they are. Regenerate with, against that release's places files:

    SELECT taxonomy.primary, arg_max(categories.primary, n) FROM (
      SELECT taxonomy, categories, count(*) n FROM read_parquet([...])
      GROUP BY ALL) GROUP BY 1 HAVING arg_max(...) <> taxonomy.primary
"""
from __future__ import annotations

import os
import re
from typing import Any

# Parquet key-value metadata key holding the release a file was cut from.
KV_RELEASE = "overture_release"
_RELEASE_IN_NAME = re.compile(r"-(\d{4}-\d{2}-\d{2}\.\d+)\.parquet$")


def parquet_release(path: str) -> str | None:
    """The release recorded in the parquet's key-value metadata, or None
    (older downloads, other writers, unreadable file)."""
    try:
        import duckdb
        lit = path.replace("'", "''")
        rows = duckdb.connect().execute(
            "SELECT key::VARCHAR, value::VARCHAR "
            f"FROM parquet_kv_metadata('{lit}')").fetchall()
    except Exception:
        return None
    for key, value in rows:
        if key == KV_RELEASE and value:
            return str(value)
    return None


def overture_release(path: str | None) -> str | None:
    """The release of an Overture parquet: its metadata, else the
    ``-<release>.parquet`` suffix the ops wrappers name files with."""
    if not path:
        return None
    rel = parquet_release(path)
    if rel:
        return rel
    m = _RELEASE_IN_NAME.search(os.path.basename(path))
    return m.group(1) if m else None


def overture_category(categories: Any, taxonomy: Any) -> str:
    """The place's primary category in the pre-2026-09-23 vocabulary.

    ``categories.primary`` when the release has it (unchanged behaviour
    up to 2026-08-19.0), else ``taxonomy.primary`` mapped back through
    TAXONOMY_TO_LEGACY. Empty string when neither is set."""
    if isinstance(categories, dict):
        primary = (categories.get("primary") or "").strip()
        if primary:
            return primary
    if isinstance(taxonomy, dict):
        primary = (taxonomy.get("primary") or "").strip()
        if primary:
            return TAXONOMY_TO_LEGACY.get(primary, primary)
    return ""


TAXONOMY_TO_LEGACY: dict[str, str] = {
    "abuse_and_addiction_treatment_center": "abuse_and_addiction_treatment",
    "adoption_service": "adoption_services",
    "adult_education_center": "adult_education",
    "adult_entertainment_venue": "adult_entertainment",
    "aerial_tour": "aerial_tours",
    "aesthetic_medicine": "aesthetician",
    "afghani_restaurant": "afghan_restaurant",
    "agricultural_cooperative": "agricultural_cooperatives",
    "agritourism": "agriturismo",
    "aircraft_service": "aircraft_repair",
    "airport_shuttle": "airport_shuttles",
    "airsoft_field": "airsoft_fields",
    "allergy_and_immunology": "allergist",
    "amateur_sport_league": "amateur_sports_league",
    "amateur_sport_team": "amateur_sports_team",
    "ambulance_or_ems_service": "ambulance_and_ems_services",
    "anesthesiology": "anesthesiologist",
    "anglican_or_episcopal_place_of_worship": "anglican_church",
    "animal_or_pet_service": "pet_services",
    "apartment": "apartments",
    "apiary_beekeeper": "apiaries_and_beekeepers",
    "apparel_manufacturer": "b2b_apparel",
    "appellate_practice_lawyer": "appellate_practice_lawyers",
    "appraisal_service": "appraisal_services",
    "aquarium_service": "aquarium_services",
    "archaeological_service": "archaeological_services",
    "archery_store": "archery_shop",
    "architectural_tour": "architectural_tours",
    "architecture_school": "architecture_schools",
    "art_tour": "art_tours",
    "arts_and_crafts_space": "chamber_of_handicraft",
    "arts_crafts_and_hobby_store": "arts_and_crafts",
    "astrological_advising": "astrologer",
    "atm": "atms",
    "attorney_or_law_firm": "lawyer",
    "atv_rental_tour": "atv_rentals_and_tours",
    "audiology": "audiologist",
    "auto_broker": "car_broker",
    "auto_dealer": "car_dealer",
    "auto_leasing": "automobile_leasing",
    "auto_manufacturer": "auto_manufacturers_and_distributors",
    "auto_parts_store": "auto_parts_and_supply_store",
    "auto_restoration_service": "auto_restoration_services",
    "automation_service": "automation_services",
    "automotive_service": "automotive_services_and_repair",
    "b2b_advertising_and_marketing_service": "business_advertising",
    "b2b_agriculture_service": "b2b_agriculture_and_food",
    "b2b_audio_visual_production": "audio_visual_production_and_design",
    "b2b_background_check_service": "background_check_services",
    "b2b_business_management_service": "business_management_services",
    "b2b_clinical_lab": "clinical_laboratories",
    "b2b_coal_and_coke": "coal_and_coke",
    "b2b_dairy": "b2b_dairies",
    "b2b_dental_lab": "dental_laboratories",
    "b2b_direct_mail_advertising": "direct_mail_advertising",
    "b2b_domestic_trade_service": "domestic_business_and_trade_organizations",
    "b2b_energy_and_utility_service": "b2b_energy_and_mining",
    "b2b_environmental_service": "wood_and_pulp",
    "b2b_executive_search_consultants": "executive_search_consultants",
    "b2b_farm": "b2b_farms",
    "b2b_hospital_equipment_and_supplies": "hospital_equipment_and_supplies",
    "b2b_human_resource_service": "human_resource_services",
    "b2b_industrial_and_machine_service": "scrap_metals",
    "b2b_international_trade_service": "international_business_and_trade_services",
    "b2b_marketing_consultant": "marketing_consultant",
    "b2b_medical_support_service": "b2b_medical_support_services",
    "b2b_mining": "mining",
    "b2b_newspaper_advertising": "newspaper_advertising",
    "b2b_oil_and_gas": "oil_and_gas",
    "b2b_oil_and_gas_equipment": "oil_and_gas_field_equipment_and_services",
    "b2b_oil_and_gas_exploration_and_development": "oil_and_gas_exploration_and_development",
    "b2b_oil_and_gas_extraction": "b2b_oil_and_gas_extraction_and_services",
    "b2b_oil_refinery": "oil_refiners",
    "b2b_outdoor_advertising": "outdoor_advertising",
    "b2b_power_plants_and_power_plant_service": "power_plants_and_power_plant_service",
    "b2b_promotional_products_and_services": "promotional_products_and_services",
    "b2b_publicity_service": "publicity_service",
    "b2b_quarry": "quarries",
    "b2b_radio_and_television_commercials": "radio_and_television_commercials",
    "b2b_records_storage_service": "business_records_storage_and_management",
    "b2b_science_and_technology_service": "b2b_science_and_technology",
    "b2b_scientific_lab": "scientific_laboratories",
    "b2b_secretarial_service": "secretarial_services",
    "b2b_service": "business_to_business",
    "b2b_signage_service": "business_signage",
    "b2b_storage": "b2b_storage_and_warehouses",
    "b2b_surgical_appliances_and_supplies": "surgical_appliances_and_supplies",
    "b2b_telemarketing_service": "telemarketing_services",
    "b2b_transportation_and_storage_service": "business_storage_and_transportation",
    "b2b_water_treatment_service": "water_treatment_equipment_and_services",
    "baby_gear_and_nursery_store": "baby_gear_and_furniture",
    "backflow_service": "backflow_services",
    "balloon_port": "balloon_ports",
    "balloon_service": "balloon_services",
    "band_orchestra_symphony": "musical_band_orchestras_and_symphonies",
    "bank": "banks",
    "bank_or_credit_union": "bank_credit_union",
    "baptist_place_of_worship": "baptist_church",
    "bar_tabac": "tabac",
    "barre_class": "barre_classes",
    "bathroom_fixture_store": "bathroom_fixture_stores",
    "bathtub_and_sink_repair": "bathtub_and_sink_repairs",
    "bazaar": "bazaars",
    "beach_equipment_rental": "beach_equipment_rentals",
    "beauty_supply_store": "cosmetic_and_beauty_supplies",
    "bedding_and_bath_store": "bedding_and_bath_stores",
    "beer_tour": "beer_tours",
    "beer_wine_spirits_store": "beer_wine_and_spirits",
    "behavior_analysis": "behavior_analyst",
    "behavioral_or_mental_health_clinic": "counseling_and_mental_health",
    "bike_path": "bicycle_path",
    "bike_rental": "bike_rentals",
    "bike_sharing_location": "bicycle_sharing_location",
    "bike_store": "bicycle_shop",
    "bike_tour": "bike_tours",
    "billing_service": "billing_services",
    "bird_store": "bird_shop",
    "blacksmith": "blacksmiths",
    "blueprinter": "blueprinters",
    "board_of_education_office": "board_of_education_offices",
    "boat_and_ship_manufacturer": "boat_builder",
    "boat_parts_store": "boat_parts_and_supply_store",
    "boat_service": "boat_service_and_repair",
    "boat_tour": "boat_tours",
    "boating_place": "boating_places",
    "books_music_and_video_store": "books_mags_music_and_video",
    "boudoir_photography_service": "boudoir_photography",
    "broker": "brokers",
    "bubble_tea_shop": "bubble_tea",
    "buddhist_place_of_worship": "buddhist_temple",
    "builder": "builders",
    "building_or_construction_service": "construction_services",
    "bus_rental": "bus_rentals",
    "bus_tour": "bus_tours",
    "business_broker": "business_brokers",
    "business_school": "business_schools",
    "camera_and_photography_store": "photography_store_and_services",
    "car_rental_service": "car_rental_agency",
    "cardio_class": "cardio_classes",
    "cardiology": "cardiologist",
    "cardiothoracic_surgery": "cardiovascular_and_thoracic_surgeon",
    "casting_molding_service": "casting_molding_and_machining",
    "cemetery": "cemeteries",
    "cheese_tasting_class": "cheese_tasting_classes",
    "child_psychiatry": "child_psychiatrist",
    "chiropractic": "chiropractor",
    "christian_place_of_worship": "church_cathedral",
    "christmas_tree_store": "christmas_trees",
    "circus_venue": "circus",
    "civic_organization": "organization",
    "civil_engineer": "civil_engineers",
    "civil_rights_lawyer": "civil_rights_lawyers",
    "cleaning_service": "cleaning_services",
    "coin_dealer": "coin_dealers",
    "collection_agency": "collection_agencies",
    "colonic_hydrotherapy": "colonics",
    "community_and_government": "public_service_and_government",
    "community_garden": "community_gardens",
    "complementary_and_alternative_medicine": "alternative_medicine",
    "corporate_entertainment_service": "corporate_entertainment_services",
    "corporate_or_business_office": "corporate_office",
    "cosmetic_dentistry": "cosmetic_dentist",
    "cosmetic_surgery": "cosmetic_surgeon",
    "cosmetics_and_fragrance_store": "perfume_store",
    "courier_and_delivery_service": "courier_and_delivery_services",
    "cpr_class": "cpr_classes",
    "craft_store": "craft_shop",
    "crane_service": "crane_services",
    "cremation_service": "cremation_services",
    "crisis_intervention_service": "crisis_intervention_services",
    "custom_clothing_store": "custom_clothing",
    "customized_merchandise_store": "customized_merchandise",
    "cycling_class": "cycling_classes",
    "dairy_store": "dairy_stores",
    "dance_studio": "dance_school",
    "dancewear_store": "dance_wear",
    "debt_relief_service": "debt_relief_services",
    "dental_clinic": "dentist",
    "dental_hygiene": "dental_hygienist",
    "dentistry_school": "dentistry_schools",
    "dermatology": "dermatologist",
    "dessert_shop": "desserts",
    "digitizing_service": "digitizing_services",
    "distribution_service": "distribution_services",
    "dive_store": "dive_shop",
    "doctors_office": "diagnostic_services",
    "dog_walker": "dog_walkers",
    "doner_kebab_restaurant": "doner_kebab",
    "donut_shop": "donuts",
    "doula_service": "doula",
    "drinking_fountain": "drinking_water_dispenser",
    "drywall_service": "drywall_services",
    "dumpster_rental": "dumpster_rentals",
    "duplication_service": "duplication_services",
    "duty_free_store": "duty_free_shop",
    "eating_disorder_treatment_center": "eating_disorder_treatment_centers",
    "editorial_service": "editorial_services",
    "educational_service": "educational_services",
    "electronic_equipment_supplier": "b2b_electronic_equipment",
    "electronics_store": "electronics",
    "embroidery_and_crochet_store": "embroidery_and_crochet",
    "emergency_department": "emergency_room",
    "emergency_or_urgent_care_facility": "emergency_medicine",
    "empanada_restaurant": "empanadas",
    "employment_agency": "employment_agencies",
    "endocrinology": "endocrinologist",
    "endodontics": "endodontist",
    "endoscopy": "endoscopist",
    "energy_management_service": "energy_management_and_conservation_consultants",
    "engineering_school": "engineering_schools",
    "engineering_service": "engineering_services",
    "environmental_abatement_service": "environmental_abatement_services",
    "environmental_or_ecological_service": "environmental_and_ecological_services_for_businesses",
    "environmental_testing_service": "environmental_testing",
    "erotic_massage_venue": "erotic_massage",
    "escape_room": "escape_rooms",
    "escrow_service": "escrow_services",
    "ethical_grocery_store": "ethical_grocery",
    "event_or_party_service": "event_planning",
    "event_photography_service": "event_photography",
    "event_venue": "venue_and_event_space",
    "exhibition_and_trade_fair_venue": "exhibition_and_trade_center",
    "exporter": "exporters",
    "eyewear_store": "eyewear_and_optician",
    "fairgrounds": "fair",
    "family_counseling": "family_counselor",
    "farming_service": "farming_services",
    "farrier_service": "farrier_services",
    "fashion_and_apparel_store": "fashion",
    "fashion_boutique": "boutique",
    "fertility_clinic": "fertility",
    "festival_venue": "festival",
    "film_festival_venue": "film_festivals_and_organizations",
    "fire_station": "fire_department",
    "fireworks_store": "firework_retailer",
    "fish_farm_hatchery": "fish_farms_and_hatcheries",
    "fitness_exercise_store": "fitness_exercise_equipment",
    "flatbread_shop": "flatbread_restaurant",
    "flooring_contractor": "flooring_contractors",
    "flower_market": "flower_markets",
    "flowers_and_gifts_store": "flowers_and_gifts_shop",
    "food_and_beverage_store": "food",
    "food_and_drink": "eat_and_drink",
    "food_bank": "food_banks",
    "food_beverage_distributor": "food_beverage_service_distribution",
    "food_tour": "food_tours",
    "food_truck_stand": "food_truck",
    "fortune_telling": "fortune_telling_service",
    "foster_care_service": "foster_care_services",
    "frozen_foods_store": "frozen_foods",
    "frozen_yogurt_shop": "frozen_yoghurt_shop",
    "funeral_service": "funeral_services_and_cemeteries",
    "furniture_manufacturer": "furniture_manufacturers",
    "furniture_wholesaler": "furniture_wholesalers",
    "gastroenterology": "gastroenterologist",
    "gelato_shop": "gelato",
    "gemstone_and_mineral_store": "gemstone_and_mineral",
    "genealogist": "genealogists",
    "genetics": "geneticist",
    "geographic_entities": "structure_and_geography",
    "geological_service": "geological_services",
    "gerontology": "gerontologist",
    "glass_blowing_venue": "glass_blowing",
    "glider_port": "gliderports",
    "golf_equipment_store": "golf_equipment",
    "government_office": "central_government_office",
    "grain_elevator": "grain_elevators",
    "gravel_professional": "gravel_professionals",
    "greenhouse": "greenhouses",
    "grilling_equipment_store": "grilling_equipment",
    "gun_and_ammo_store": "gun_and_ammo",
    "hair_supply_store": "hair_supply_stores",
    "handbag_store": "handbag_stores",
    "hardware_and_fastener_manufacturer": "b2b_hardware",
    "hardware_home_and_garden_store": "home_and_garden",
    "hat_store": "hat_shop",
    "health_care": "health_and_medical",
    "health_coaching": "health_coach",
    "health_retreat": "health_retreats",
    "hearing_aid_store": "hearing_aid_provider",
    "heliport": "heliports",
    "hepatology": "hepatologist",
    "herb_and_spice_store": "herb_and_spice_shop",
    "himalayan_restaurant": "himalayan_nepalese_restaurant",
    "hindu_place_of_worship": "hindu_temple",
    "historic_mission": "mission",
    "historic_site": "landmark_and_historical_building",
    "historic_tower": "tower",
    "historical_tour": "historical_tours",
    "hockey_equipment_store": "hockey_equipment",
    "holding_company": "holding_companies",
    "holiday_decor_store": "holiday_decor",
    "holiday_decorating_service": "holiday_decorating",
    "home_decor_store": "home_decor",
    "homeopathy": "homeopathic_medicine",
    "hot_tub_and_pool_store": "hot_tubs_and_pools",
    "housing_authority": "housing_authorities",
    "hunting_and_fishing_store": "hunting_and_fishing_supplies",
    "hvac_service": "hvac_services",
    "hydroponic_gardening_store": "hydroponic_gardening",
    "hyperbaric_medicine": "undersea_hyperbaric_medicine",
    "hypnotherapy": "hypnosis_hypnotherapy",
    "immigration_and_naturalization_office": "immigration_and_naturalization",
    "immigration_assistance_service": "immigration_assistance_services",
    "immunodermatology": "immunodermatologist",
    "import_export_service": "importer_and_exporter",
    "imported_food_store": "imported_food",
    "importer": "importers",
    "industrial_cleaning_service": "industrial_cleaning_services",
    "industrial_equipment_manufacturer": "industrial_equipment",
    "infectious_disease": "infectious_disease_specialist",
    "inspection_service": "inspection_services",
    "instrumentation_engineer": "instrumentation_engineers",
    "international_fusion_restaurant": "international_restaurant",
    "ironworker": "ironworkers",
    "irrigation_service": "irrigation",
    "jail_or_prison": "jail_and_prison",
    "janitorial_service": "janitorial_services",
    "jazz_and_blues_venue": "jazz_and_blues",
    "jehovahs_witness_place_of_worship": "jehovahs_witness_kingdom_hall",
    "jewish_place_of_worship": "synagogue",
    "karaoke_venue": "karaoke",
    "kitchen_and_bath_store": "kitchen_and_bath",
    "knitting_supply_store": "knitting_supply",
    "kombucha_bar": "kombucha",
    "lactation_service": "lactation_services",
    "laser_cutting_service": "laser_cutting_service_provider",
    "laundry_service": "laundry_services",
    "law_school": "law_schools",
    "leather_goods_store": "leather_goods",
    "legal_service": "legal_services",
    "light_rail_and_subway_station": "light_rail_and_subway_stations",
    "lighting_fixture_manufacturer": "lighting_fixture_manufacturers",
    "lime_professional": "lime_professionals",
    "limo_service": "limo_services",
    "linen_store": "linen",
    "livestock_dealer": "livestock_dealers",
    "lodging": "accommodation",
    "logging_service": "logging_services",
    "lottery_vendor": "lottery_ticket",
    "macaron_shop": "macarons",
    "machine_and_tool_rental": "machine_and_tool_rentals",
    "machinery_and_tool_manufacturer": "b2b_machinery_and_tools",
    "manufacturer": "business_manufacturing_and_supply",
    "marble_and_granite_professional": "marble_and_granite_professionals",
    "marriage_or_relationship_counseling": "marriage_or_relationship_counselor",
    "masonry_contractor": "masonry_contractors",
    "maternity_center": "maternity_centers",
    "mechanical_engineer": "mechanical_engineers",
    "media_service": "mass_media",
    "medical_billing": "bulk_billing",
    "medical_research_institute": "medical_research_and_development",
    "medical_sciences_school": "medical_sciences_schools",
    "medical_service_organization": "medical_service_organizations",
    "medical_supply_store": "medical_supply",
    "memory_care_facility": "memory_care",
    "metal_detector_service": "metal_detector_services",
    "metal_material_expert": "metal_materials_and_experts",
    "midwifery": "midwife",
    "military_site": "armed_forces_branch",
    "mill": "mills",
    "misting_system_service": "misting_system_services",
    "mobile_phone_accessory_store": "mobile_phone_accessories",
    "mobility_equipment_service": "mobility_equipment_services",
    "money_transfer_service": "money_transfer_services",
    "mortuary_service": "mortuary_services",
    "motorcycle_parts_store": "motorcycle_gear",
    "motorcycle_rental_service": "motorcycle_rentals",
    "mountain_bike_park": "mountain_bike_parks",
    "mountain_bike_trail": "mountain_bike_trails",
    "mountain_hut": "mountain_huts",
    "mover": "movers",
    "movie_theater": "cinema",
    "music_festival_venue": "music_festivals_and_organizations",
    "music_production_service": "music_production_services",
    "musical_instrument_service": "musical_instrument_services",
    "muslim_place_of_worship": "mosque",
    "nanny_service": "nanny_services",
    "national_security_service": "national_security_services",
    "natural_gas_utility_provider": "natural_gas_supplier",
    "naturist_club": "nudist_clubs",
    "naturopathic_medicine": "naturopathic_holistic",
    "nephrology": "nephrologist",
    "neurology": "neurologist",
    "neuropathology": "neuropathologist",
    "neurotology": "neurotologist",
    "non_alcoholic_beverage_venue": "beverage_store",
    "nursery_and_gardening_store": "nursery_and_gardening",
    "nursing": "skilled_nursing",
    "nutrition_service": "nutritionist",
    "obstetrics_and_gynecology": "obstetrician_and_gynecologist",
    "office_supply_store": "office_equipment",
    "officiating_service": "officiating_services",
    "olive_oil_store": "olive_oil",
    "oncology": "oncologist",
    "ophthalmology": "ophthalmologist",
    "optometry": "optometrist",
    "oral_and_maxillofacial_surgery": "oral_surgeon",
    "orthodontics": "orthodontist",
    "orthopedics": "orthopedist",
    "osteopathic_medicine": "osteopath",
    "otology": "otologist",
    "outdoor_movie_space": "outdoor_movies",
    "outdoor_store": "outdoor_gear",
    "outpatient_care_facility": "medical_center",
    "packing_service": "packing_services",
    "packing_supply_store": "packing_supply",
    "paint_and_sip_venue": "paint_and_sip",
    "paint_your_own_pottery_venue": "paint_your_own_pottery",
    "paralegal_service": "paralegal_services",
    "parenting_class": "parenting_classes",
    "park_and_ride": "park_and_rides",
    "party_supply_store": "party_supply",
    "passport_and_visa_service": "passport_and_visa_services",
    "pasta_store": "pasta_shop",
    "paternity_testing": "paternity_tests_and_services",
    "pathology": "pathologist",
    "payroll_service": "payroll_services",
    "pediatric_clinic": "pediatrician",
    "pediatric_dentistry": "pediatric_dentist",
    "pension_office": "pension",
    "pentecostal_place_of_worship": "pentecostal_church",
    "performing_arts_venue": "theaters_and_performance_venues",
    "periodontics": "periodontist",
    "persian_restaurant": "persian_iranian_restaurant",
    "personal_or_beauty_service": "personal_care_service",
    "pet_cemetery_and_crematorium_service": "pet_cemetery_and_crematorium_services",
    "pharmaceutical_company": "pharmaceutical_companies",
    "pharmacy_school": "pharmacy_schools",
    "phlebology": "phlebologist",
    "photography_class": "photography_classes",
    "photography_service": "photographer",
    "piano_service": "piano_services",
    "place_of_worship": "temple",
    "plastic_and_reconstructive_surgery": "plastic_surgeon",
    "plastic_injection_molding_service": "plastic_injection_molding_workshop",
    "plastics_company": "plastic_company",
    "plus_size_clothing_store": "plus_size_clothing",
    "police_station": "police_department",
    "pool_and_billiards_store": "pool_and_billiards",
    "pool_and_hot_tub_service": "pool_and_hot_tub_services",
    "pop_up_store": "pop_up_shop",
    "prenatal_and_perinatal_care": "prenatal_perinatal_care",
    "pretzel_shop": "pretzels",
    "printing_equipment_supplier": "printing_equipment_and_supply",
    "printing_service": "printing_services",
    "private_jet_charter": "private_jet_charters",
    "process_server": "process_servers",
    "proctology": "proctologist",
    "produce_store": "fruits_and_vegetables",
    "professional_service": "professional_services",
    "professional_sport_league": "professional_sports_league",
    "professional_sport_team": "professional_sports_team",
    "prosthodontics": "prosthodontist",
    "protestant_place_of_worship": "evangelical_church",
    "psychiatry": "psychiatrist",
    "psychic_advising": "psychic",
    "psychoanalysis": "psychoanalyst",
    "psychology": "psychologist",
    "psychomotor_therapy": "psychomotor_therapist",
    "psychotherapy": "psychotherapist",
    "public_bath_house": "public_bath_houses",
    "public_fountain": "fountain",
    "public_phone": "public_phones",
    "public_restroom": "public_restrooms",
    "public_transit_facility_or_service": "public_transportation",
    "public_utility": "public_utility_company",
    "publisher": "topic_publisher",
    "pulmonology": "pulmonologist",
    "radiology": "radiologist",
    "rail_facility_or_service": "railway_service",
    "ramen_restaurant": "noodles_restaurant",
    "recreational_trail_or_path": "trail",
    "refinishing_service": "refinishing_services",
    "refractive_surgery_or_lasik": "laser_eye_surgery_lasik",
    "religious_and_spiritual_goods_store": "religious_items",
    "rental_kiosk": "rental_kiosks",
    "reproductive_perinatal_and_womens_care": "womens_health_clinic",
    "reptile_store": "reptile_shop",
    "retina_services": "retina_specialist",
    "rheumatology": "rheumatologist",
    "rice_store": "rice_shop",
    "ride_share_service": "ride_sharing",
    "road_structures_and_service": "road_structures_and_services",
    "roman_catholic_place_of_worship": "catholic_church",
    "rubber_and_plastics_manufacturer": "b2b_rubber_and_plastics",
    "rv_parts_store": "recreational_vehicle_parts_and_accessories",
    "rv_rental_service": "rv_rentals",
    "safety_equipment_store": "safety_equipment",
    "sawmill": "saw_mill",
    "scavenger_hunt": "scavenger_hunts_provider",
    "school_district_office": "school_district_offices",
    "school_sport_league": "school_sports_league",
    "school_sport_team": "school_sports_team",
    "science_school": "science_schools",
    "scooter_dealer": "scooter_dealers",
    "scooter_tour": "scooter_tours",
    "seaplane_base": "seaplane_bases",
    "second_hand_clothing_store": "used_vintage_and_consignment",
    "second_hand_store": "thrift_store",
    "security_service": "security_services",
    "self_defense_class": "self_defense_classes",
    "senior_citizen_service": "senior_citizen_services",
    "septic_service": "septic_services",
    "service_apartment": "service_apartments",
    "session_photography_service": "session_photography",
    "sex_therapy": "sex_therapist",
    "sheet_metal_fabricator": "sheet_metal",
    "shinto_shrine": "shinto_shrines",
    "shipping_collection_service": "shipping_collection_services",
    "shoe_factory_manufacturer": "shoe_factory",
    "shopping_mall": "shopping_center",
    "shredding_service": "shredding_services",
    "sikh_place_of_worship": "sikh_temple",
    "skate_store": "skate_shop",
    "ski_and_snowboard_store": "ski_and_snowboard_shop",
    "skin_care_and_makeup": "skin_care",
    "sleep_medicine": "sleep_specialist",
    "smoke_and_vape_store": "e_cigarette_store",
    "social_and_human_service": "social_and_human_services",
    "social_or_community_service": "community_services_non_profits",
    "social_security_service": "social_security_services",
    "southern_american_restaurant": "southern_restaurant",
    "souvenir_store": "souvenir_shop",
    "spa": "spas",
    "specialized_health_care": "physician_assistant",
    "specialty_foods_store": "specialty_foods",
    "specialty_store": "props",
    "speech_therapy": "speech_therapist",
    "spine_surgery": "spine_surgeon",
    "spiritual_advising": "mystic",
    "sport_equipment_rental": "sport_equipment_rentals",
    "sport_or_fitness_facility": "sports_and_recreation_venue",
    "sport_or_recreation_club": "sports_club_and_league",
    "sporting_goods_manufacturer": "b2b_sporting_and_recreation_goods",
    "sporting_goods_store": "sporting_goods",
    "sports_and_recreation": "active_life",
    "sports_psychology": "sports_psychologist",
    "sportswear_store": "sports_wear",
    "steel_fabricator": "steel_fabricators",
    "stock_and_bond_broker": "stock_and_bond_brokers",
    "stress_management_service": "stress_management_services",
    "stucco_service": "stucco_services",
    "suicide_prevention_service": "suicide_prevention_services",
    "supplier_or_distributor": "business_equipment_and_supply",
    "surf_store": "surf_shop",
    "surgery": "surgeon",
    "surgery_center": "surgical_center",
    "t_shirt_printing_service": "screen_printing_t_shirt_printing",
    "tabletop_games_store": "tabletop_games",
    "tailor": "gents_tailor",
    "tasting_class": "tasting_classes",
    "tax_service": "tax_services",
    "taxi_stand": "taxi_rank",
    "telecommunications_service": "telecommunications",
    "telephone_service": "telephone_services",
    "television_service_provider": "television_service_providers",
    "textile_manufacturer": "b2b_textiles",
    "theatre_venue": "theatre",
    "theatrical_production": "theatrical_productions",
    "ticket_office_or_booth": "ticket_sales",
    "tires_manufacturer": "b2b_tires",
    "toll_station": "toll_stations",
    "tour_operator": "tours",
    "toxicology": "toxicologist",
    "tractor_dealer": "b2b_tractor_dealers",
    "trailer_rental_service": "trailer_rentals",
    "train": "trains",
    "transcription_service": "transcription_services",
    "translating_and_interpreting_service": "translating_and_interpreting_services",
    "translation_service": "translation_services",
    "travel_agent": "travel_agents",
    "travel_and_transportation": "transportation",
    "travel_service": "travel_services",
    "tree_service": "tree_services",
    "trophy_store": "trophy_shop",
    "truck_and_industrial_vehicle_services": "trucks_and_industrial_vehicles",
    "truck_parts_and_accessories": "b2b_truck_equipment_parts_and_accessories",
    "truck_rental_service": "truck_rentals",
    "tutoring_service": "tutoring_center",
    "typing_service": "typing_services",
    "ultralight_airport": "ultralight_airports",
    "ultrasound_imaging": "ultrasound_imaging_center",
    "urology": "urologist",
    "used_auto_dealer": "used_car_dealer",
    "vacation_rental_agent": "vacation_rental_agents",
    "vehicle_dealer": "automotive_dealer",
    "vehicle_manufacturer": "b2b_autos_and_vehicles",
    "veterinary_school": "veterinary_schools",
    "video_and_video_game_rental": "video_and_video_game_rentals",
    "vision_or_eye_care_clinic": "eye_care_clinic",
    "vitamin_and_supplement_store": "vitamins_and_supplements",
    "walking_tour": "walking_tours",
    "wallpaper_installer": "wallpaper_installers",
    "warehouse": "warehouses",
    "warehouse_club_store": "wholesale_store",
    "warehouse_rental_service_yard": "warehouse_rental_services_and_yards",
    "water_purification_service": "water_purification_services",
    "water_taxi_service": "water_taxi",
    "water_utility_provider": "water_supplier",
    "weather_forecast_service": "weather_forecast_services",
    "welder": "welders",
    "wellness_service": "wellness_program",
    "whale_watching_tour": "whale_watching_tours",
    "wine_tasting_class": "wine_tasting_classes",
    "wine_tour": "wine_tours",
    "youth_organization": "youth_organizations",
}
