"""Overture release and schema helpers shared by download_overture_data.py
and the merges in streetzim/addresses.py.

Release: download_overture_data.py writes the release a parquet was cut
from into its key-value metadata (``overture_release``); the ops wrappers
also put it in the file name (``places-<id>-<release>.parquet``).

Places categories: Overture removed ``categories`` (``primary`` /
``alternate``) in release 2026-09-23.0. Its replacement ``taxonomy``
(``primary`` / ``hierarchy`` / ``alternates``) names the same leaf
categories, 607 of them spelled differently ("dentist" is now
"dental_clinic", "car_dealer" "auto_dealer", "accommodation" "lodging").
The search records' ``cat`` / ``s`` values, the chip rules
(cloud/chip_rules.py), the viewer's icons and labels, and the generic-bucket
refinement in merge_overture_places all use the old names, so
``taxonomy.primary`` is mapped back to them. ``basic_category`` is coarser
(e.g. "wellness_service" for "spas") and is not used.

The tables live in streetzim/overture_taxonomy.py, generated by
tools/gen_taxonomy_legacy.py from release 2026-08-19.0, which carries both
columns: TAXONOMY_TO_LEGACY (the 607 taxonomy names that differ) and
LEGACY_NAMES (the 1984 old names). Over its 70.3 M categorised places the
pairing is one-to-one except for 4 rows, where the majority pairing is kept:
health_care -> eat_and_drink (2 rows; kept health_and_medical), lodging ->
eat_and_drink (1; kept accommodation) and sports_and_recreation ->
health_and_medical (1; kept active_life). No old name is reused as a
different new name.

A taxonomy name newer than 2026-08-19.0 (130 in 2026-09-23.1, e.g.
"general_hospital", "counseling") is replaced by its nearest ancestor in
``taxonomy.hierarchy`` that has an old name ("hospital",
"counseling_and_mental_health"), so it lands in the same chips as before;
with no such ancestor the leaf is kept.
"""
from __future__ import annotations

import os
import re
from typing import Any

# Where DuckDB keeps its extensions (spatial, httpfs). Default: ~/.duckdb,
# which a non-root `docker run --user` cannot write or may not have; the
# Docker image installs them in /opt/duckdb-ext and sets this to it.
DUCKDB_EXT_ENV = "STREETZIM_DUCKDB_EXT"


def duckdb_connect() -> Any:
    """An in-memory DuckDB connection that finds its extensions in
    $STREETZIM_DUCKDB_EXT when that is set."""
    import duckdb
    con = duckdb.connect()
    ext = os.environ.get(DUCKDB_EXT_ENV)
    if ext:
        con.execute("SET extension_directory = '" + ext.replace("'", "''") + "'")
    return con

from streetzim.overture_taxonomy import LEGACY_NAMES, TAXONOMY_TO_LEGACY

# Parquet key-value metadata key holding the release a file was cut from.
KV_RELEASE = "overture_release"
_RELEASE_IN_NAME = re.compile(r"-(\d{4}-\d{2}-\d{2}\.\d+)\.parquet$")


def parquet_release(path: str) -> str | None:
    """The release recorded in the parquet's key-value metadata, or None
    (older downloads, other writers, unreadable file)."""
    try:
        import duckdb
        lit = path.replace("'", "''")
        rows = duckdb.connect().execute(
            "SELECT key::VARCHAR, value::VARCHAR "
            f"FROM parquet_kv_metadata('{lit}')").fetchall()
    except Exception:
        return None
    for key, value in rows:
        if key == KV_RELEASE and value:
            return str(value)
    return None


def overture_release(path: str | None) -> str | None:
    """The release of an Overture parquet: its metadata, else the
    ``-<release>.parquet`` suffix the ops wrappers name files with."""
    if not path:
        return None
    rel = parquet_release(path)
    if rel:
        return rel
    m = _RELEASE_IN_NAME.search(os.path.basename(path))
    return m.group(1) if m else None


def _legacy(name: str) -> str | None:
    """The old name for a taxonomy name, or None if it has none."""
    if name in TAXONOMY_TO_LEGACY:
        return TAXONOMY_TO_LEGACY[name]
    return name if name in LEGACY_NAMES else None


def overture_category(categories: Any, taxonomy: Any) -> str:
    """The place's primary category in the pre-2026-09-23 vocabulary.

    ``categories.primary`` when the release has it (unchanged behaviour
    up to 2026-08-19.0), else ``taxonomy.primary`` mapped back to its old
    name; a leaf with none takes its nearest ancestor's in
    ``taxonomy.hierarchy``, else stays as it is. Empty string when neither
    column is set."""
    if isinstance(categories, dict):
        primary = (categories.get("primary") or "").strip()
        if primary:
            return primary
    if not isinstance(taxonomy, dict):
        return ""
    leaf = (taxonomy.get("primary") or "").strip()
    if not leaf:
        return ""
    mapped = _legacy(leaf)
    if mapped:
        return mapped
    hierarchy = taxonomy.get("hierarchy") or []
    for name in reversed(list(hierarchy)):
        mapped = _legacy(name) if isinstance(name, str) and name != leaf else None
        if mapped:
            return mapped
    return leaf
