#!/usr/bin/env python3
"""Collect the viewer's UI strings and inline the translation tables.

The viewer's English lives at its call sites -- ``szT('key', 'English')``,
``szTn('key', n, {one: '…', other: '…'})`` and ``data-i18n="key"`` on
static markup -- so code and English cannot drift. This tool:

1. collects them from resources/viewer/src/index/* and places.html into
   resources/viewer/i18n/en.json (the translators' source, and what the
   build side can read);
2. writes the runtime (resources/viewer/i18n/runtime.js) plus every
   language table (resources/viewer/i18n/<lang>.json, en excluded) into
   index.html's part 005-i18n.html and between places.html's SZ-I18N
   markers. Each page gets only the keys it uses.

The tables are inlined, not shipped as files: a published ZIM can never
gain a file, and in-place patches rewrite only the viewer slots
(docs/viewer-slots.md).

    python tools/build_i18n.py          # rewrite en.json + the inlined blocks
    python tools/build_i18n.py --check  # fail if anything is out of date

tools/build_viewer.py runs this first, so the usual
``python tools/build_viewer.py`` covers it. See docs/i18n.md.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from html.parser import HTMLParser
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
VIEWER = ROOT / "resources" / "viewer"
PARTS = VIEWER / "src" / "index"
PLACES = VIEWER / "places.html"
I18N = VIEWER / "i18n"
RUNTIME = I18N / "runtime.js"
EN_JSON = I18N / "en.json"
PART_OUT = PARTS / "005-i18n.html"
PLACES_BEGIN = "<!-- SZ-I18N BEGIN: generated by tools/build_i18n.py from resources/viewer/i18n -->"
PLACES_END = "<!-- SZ-I18N END -->"

# Key: dotted lower-case words, e.g. "routing.status.no_route".
KEY = r"[a-z0-9_]+(?:\.[a-z0-9_]+)+"
# Keys looked up by a computed name, so no call site carries them: place
# types (runtime.js szPlaceType: "type.<OSM key>"). Their English is the
# key itself; a table may hold any of them, and both pages get them all.
DYNAMIC_FAMILIES = ("type.",)
PLURAL_CATEGORIES = ("zero", "one", "two", "few", "many", "other")

class I18nError(Exception):
    pass


_ESC = {"n": "\n", "t": "\t", "r": "\r", "b": "\b", "f": "\f", "v": "\v", "0": "\0"}


def _read_literal(src: str, i: int) -> tuple[str, int]:
    """Parse a JS string literal ('…', "…" or a `…` with no ${}) at src[i];
    return (value, index after it)."""
    q = src[i]
    if q not in "'\"`":
        raise I18nError(f"expected a string literal at {_where(src, i)}")
    out: list[str] = []
    j = i + 1
    while j < len(src):
        c = src[j]
        if c == q:
            return "".join(out), j + 1
        if c == "\\":
            n = src[j + 1]
            if n == "u":
                if src[j + 2] == "{":
                    end = src.index("}", j)
                    out.append(chr(int(src[j + 3:end], 16)))
                    j = end + 1
                else:
                    out.append(chr(int(src[j + 2:j + 6], 16)))
                    j += 6
                continue
            if n == "x":
                out.append(chr(int(src[j + 2:j + 4], 16)))
                j += 4
                continue
            if n == "\n":
                j += 2
                continue
            out.append(_ESC.get(n, n))
            j += 2
            continue
        if q == "`" and c == "$" and src[j + 1:j + 2] == "{":
            raise I18nError(f"English text must not interpolate (${{}}): {_where(src, i)}")
        if c == "\n" and q != "`":
            raise I18nError(f"unterminated string at {_where(src, i)}")
        out.append(c)
        j += 1
    raise I18nError(f"unterminated string at {_where(src, i)}")


def _skip_ws(src: str, i: int) -> int:
    while i < len(src):
        if src[i].isspace():
            i += 1
        elif src.startswith("//", i):
            i = src.index("\n", i)
        elif src.startswith("/*", i):
            i = src.index("*/", i) + 2
        else:
            break
    return i


def _read_concat(src: str, i: int) -> tuple[str, int]:
    """'a' + 'b' + … -> 'ab' (only literals: the English must be static)."""
    i = _skip_ws(src, i)
    s, i = _read_literal(src, i)
    while True:
        j = _skip_ws(src, i)
        if j < len(src) and src[j] == "+":
            k = _skip_ws(src, j + 1)
            if k < len(src) and src[k] in "'\"`":
                t, i = _read_literal(src, k)
                s += t
                continue
            raise I18nError(f"English text must be literals only: {_where(src, j)}")
        return s, i


def _where(src: str, i: int) -> str:
    line = src.count("\n", 0, i) + 1
    return f"line {line}: {src[max(0, i - 30):i + 50]!r}"


def _in_comment(src: str, i: int) -> bool:
    """Is src[i] in a // line comment or a /* */ block line? Good enough for
    the viewer's style (comments never share a line with a call)."""
    line = src[src.rfind("\n", 0, i) + 1:i]
    t = line.lstrip()
    return t.startswith(("//", "*", "/*")) or bool(re.search(r"(^|\s)//", line))


_CALL = re.compile(r"\bszT(n?)\(\s*(['\"])(" + KEY + r")\2\s*,")


def collect_js(src: str, origin: str) -> dict[str, Any]:
    """Every szT / szTn call in `src` -> {key: English}."""
    found: dict[str, Any] = {}
    for m in _CALL.finditer(src):
        if _in_comment(src, m.start()):
            continue
        plural, key = m.group(1) == "n", m.group(3)
        i = m.end()
        try:
            if not plural:
                val: Any = _read_concat(src, i)[0]
            else:
                # szTn('key', <count expr>, { one: '…', other: '…' } ...)
                ob = src.find("{", i)
                if ob < 0 or ob - i > 160:
                    raise I18nError(f"szTn needs a literal {{one:…, other:…}}: {_where(src, i)}")
                val = {}
                j = ob + 1
                while True:
                    j = _skip_ws(src, j)
                    if src[j] == "}":
                        break
                    km = re.match(r"(\w+)\s*:", src[j:])
                    if not km or km.group(1) not in PLURAL_CATEGORIES:
                        raise I18nError(f"bad plural form in szTn: {_where(src, j)}")
                    s, j = _read_concat(src, j + km.end())
                    val[km.group(1)] = s
                    j = _skip_ws(src, j)
                    if src[j] == ",":
                        j += 1
                if set(val) != {"one", "other"}:
                    raise I18nError(f"szTn English forms must be one + other: {_where(src, i)}")
        except I18nError as e:
            raise I18nError(f"{origin}: {e}") from None
        _add(found, key, val, origin)
    # A call whose key is not a literal can't be collected or checked.
    for m in re.finditer(r"(?<!function )\bszTn?\(\s*(?!['\"]" + KEY + r"['\"])", src):
        end = src.find("\n", m.start())
        if _in_comment(src, m.start()) or "i18n-dynamic" in src[m.start():end]:
            continue  # szApplyI18n's lookups of data-i18n keys (collected from the markup)
        raise I18nError(f"{origin}: szT/szTn needs a literal dotted key: {_where(src, m.start())}")
    return found


def _add(found: dict[str, Any], key: str, val: Any, origin: str) -> None:
    if key in found and found[key] != val:
        raise I18nError(f"{origin}: key {key!r} has two English texts: {found[key]!r} / {val!r}")
    found[key] = val


class _Markup(HTMLParser):
    """data-i18n* attributes and the English they carry."""

    VOID = frozenset({"area", "base", "br", "col", "embed", "hr", "img", "input", "link",
                      "meta", "source", "track", "wbr"})

    def __init__(self, origin: str) -> None:
        super().__init__(convert_charrefs=True)
        self.origin = origin
        self.found: dict[str, Any] = {}
        self.stack: list[tuple[str, str | None, list[str]]] = []
        self.in_script = False

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if tag in ("script", "style"):
            self.in_script = True
            return
        a = dict(attrs)
        for name in ("title", "placeholder", "aria-label"):
            k = a.get("data-i18n-" + name)
            if k:
                if not re.fullmatch(KEY, k) or a.get(name) is None:
                    raise I18nError(f"{self.origin}: data-i18n-{name}={k!r} needs a key and a {name}=")
                _add(self.found, k, _norm(a.get(name) or ""), self.origin)
        if tag in self.VOID:
            if a.get("data-i18n"):
                raise I18nError(f"{self.origin}: data-i18n on <{tag}>")
            return
        key = a.get("data-i18n")
        if key is not None and not re.fullmatch(KEY, key):
            raise I18nError(f"{self.origin}: bad data-i18n key {key!r}")
        self.stack.append((tag, key, []))

    def handle_endtag(self, tag: str) -> None:
        if tag in ("script", "style"):
            self.in_script = False
            return
        while self.stack:
            t, key, buf = self.stack.pop()
            text = "".join(buf)
            if key:
                _add(self.found, key, _norm(text), self.origin)
            if self.stack:
                self.stack[-1][2].append(text)
            if t == tag:
                break

    def handle_data(self, data: str) -> None:
        if not self.in_script and self.stack:
            self.stack[-1][2].append(data)


def _norm(s: str) -> str:
    return re.sub(r"\s+", " ", s).strip()


def collect_markup(src: str, origin: str) -> dict[str, Any]:
    p = _Markup(origin)
    p.feed(src)
    p.close()
    return p.found


def _strip_generated(src: str) -> str:
    """places.html without its generated block (which holds the runtime
    and the tables, not call sites)."""
    a, b = src.find(PLACES_BEGIN), src.find(PLACES_END)
    if a < 0 or b < a:
        raise I18nError(f"places.html: missing {PLACES_BEGIN!r} … {PLACES_END!r}")
    return src[:a] + src[b + len(PLACES_END):]


def collect_page(sources: list[tuple[str, str]]) -> dict[str, Any]:
    out: dict[str, Any] = {}
    for origin, src in sources:
        markup = collect_markup(src, origin) if origin.endswith(".html") else {}
        for k, v in list(collect_js(src, origin).items()) + list(markup.items()):
            _add(out, k, v, origin)
    return out


def runtime_source() -> tuple[str, str]:
    """The runtime's own strings (chip labels, number suffixes): both pages."""
    return ("runtime.js", RUNTIME.read_text(encoding="utf-8"))


def index_sources() -> list[tuple[str, str]]:
    return [runtime_source()] + [(p.name, p.read_text(encoding="utf-8")) for p in sorted(PARTS.iterdir())
                                 if not p.name.startswith(".") and p != PART_OUT]


def places_source() -> list[tuple[str, str]]:
    return [runtime_source(), ("places.html", _strip_generated(PLACES.read_text(encoding="utf-8")))]


def is_dynamic(key: str) -> bool:
    return key.startswith(DYNAMIC_FAMILIES)


def languages() -> dict[str, dict[str, Any]]:
    """Every translation table but English, by language code."""
    out = {}
    for p in sorted(I18N.glob("*.json")):
        if p.stem == "en":
            continue
        if not re.fullmatch(r"[a-z]{2,3}", p.stem):
            raise I18nError(f"{p}: name a table by its language code (de.json)")
        out[p.stem] = json.loads(p.read_text(encoding="utf-8"))
    return out


def _json(obj: Any) -> str:
    # </script> can't appear inside the inline block.
    return json.dumps(obj, ensure_ascii=False, sort_keys=True, separators=(",", ":")).replace("</", "<\\/")


def tables_for(keys: set[str], langs: dict[str, dict[str, Any]]) -> dict[str, dict[str, Any]]:
    """Each language's entries for `keys`, as inlined: the place types
    ("type.<key>") nested under one "type" object, which saves repeating
    the prefix ~260 times in a slot that is short of room."""
    out: dict[str, dict[str, Any]] = {}
    for lang, table in langs.items():
        t: dict[str, Any] = {k: v for k, v in table.items() if k in keys}
        types = {k[len("type."):]: v for k, v in table.items() if k.startswith("type.")}
        if types:
            t["type"] = types
        out[lang] = t
    return out


def _runtime_for_page() -> str:
    """runtime.js without its whole-line comments: every byte of the viewer
    slots counts (docs/viewer-slots.md), and the source keeps them."""
    lines = [ln for ln in RUNTIME.read_text(encoding="utf-8").rstrip("\n").split("\n")
             if not ln.lstrip().startswith("//") or "sz-i18n-runtime" in ln]
    lines.insert(1, "// resources/viewer/i18n/runtime.js (comments there); docs/i18n.md")
    return "\n".join(lines)


def inline_block(keys: set[str], langs: dict[str, dict[str, Any]]) -> str:
    runtime = _runtime_for_page()
    return ("<script>\n" + runtime + "\n</script>\n"
            '<script type="application/json" id="sz-i18n">'
            + _json(tables_for(keys, langs)) + "</script>\n")


def build() -> dict[Path, str]:
    """{path: wanted content} for every file this tool owns."""
    idx = collect_page(index_sources())
    plc = collect_page(places_source())
    en: dict[str, Any] = {}
    for k, v in list(idx.items()) + list(plc.items()):
        _add(en, k, v, "index.html/places.html")
    langs = languages()
    part = ("<!-- Generated by tools/build_i18n.py from resources/viewer/i18n (runtime.js\n"
            "     and the language tables); do not edit. See docs/i18n.md. -->\n"
            + inline_block(set(idx), langs))
    places = PLACES.read_text(encoding="utf-8")
    a, b = places.find(PLACES_BEGIN), places.find(PLACES_END)
    if a < 0 or b < a:
        raise I18nError(f"places.html: missing {PLACES_BEGIN!r} … {PLACES_END!r}")
    places = places[:a + len(PLACES_BEGIN)] + "\n" + inline_block(set(plc), langs) + places[b:]
    return {
        EN_JSON: json.dumps(en, ensure_ascii=False, sort_keys=True, indent=1) + "\n",
        PART_OUT: part,
        PLACES: places,
    }


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=next(iter((__doc__ or "").splitlines()), ""))
    ap.add_argument("--check", action="store_true", help="exit 1 if a generated file is stale")
    args = ap.parse_args(argv)
    try:
        want = build()
    except I18nError as e:
        print(f"build_i18n: {e}", file=sys.stderr)
        return 1
    stale = [p for p, s in want.items() if not p.exists() or p.read_text(encoding="utf-8") != s]
    if args.check:
        for p in stale:
            print(f"{p.relative_to(ROOT)} is stale: run python tools/build_viewer.py", file=sys.stderr)
        return 1 if stale else 0
    for p in stale:
        p.write_text(want[p], encoding="utf-8")
        print(f"wrote {p.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
