#!/usr/bin/env python3
"""Generate the viewer's table of combining marks (canonical combining class
not 0) from Python's unicodedata, so the viewer folds search text exactly as
the writer does (docs/search-prefix-locality.md, "Text folding").

    python tools/gen_combining_marks.py            # rewrite the table
    python tools/gen_combining_marks.py --check    # fail if it is stale (CI)

The writer's fold is cloud/search_shards.py ``norm``: NFKD, drop every
character with ``unicodedata.combining(c) != 0``, lowercase. Every published
ZIM's search index was written with it, and a new viewer is patched into old
ZIMs, so the viewer has to match it rather than the other way round. The
obvious JavaScript, ``/\\p{M}/gu``, drops *every* mark -- including Indic
vowel signs and Thai vowels, which are marks with combining class 0 -- so
"कोलकाता" folded to "कलकत" in the viewer and to "कोलकाता" in the writer,
and the viewer asked for leaves the writer never wrote. JavaScript has no
combining-class API, hence this table.

The table is written between ``// BEGIN combining-marks`` and
``// END combining-marks`` in resources/viewer/src/index/300-search.js (then
tools/build_viewer.py) and resources/viewer/places.html; both sit inside the
search-shards block, which tests/search_shards_js.test.mjs requires to be
identical in every viewer.

Unicode versions. The table records ``unicodedata.unidata_version``. It is
generated with the newest Python the project runs -- 3.14 (the Docker image
and CI's python-3-14 job, Unicode 16.0.0); the production host and CI's main
job run 3.12 (Unicode 15.0.0). Canonical combining classes are stable
(Unicode's stability policy: once a character is assigned, its class never
changes), so a newer table is a superset of an older one, differing only in
code points the older version had not assigned -- which a writer on the older
Python leaves alone and this table strips; no real name contains them. So:

* same version as the table: ``--check`` requires the block byte for byte;
* an older Python: ``--check`` requires its set to be a subset of the table,
  every extra code point unassigned in its own database (CI's 3.12 job);
* a newer Python: ``--check`` fails -- regenerate with it, so the table keeps
  following the newest version in use. Generating with an older Python than
  the table's is refused (it would drop characters) unless --allow-older.
"""
from __future__ import annotations

import argparse
import re
import sys
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TARGETS = [
    ROOT / "resources" / "viewer" / "src" / "index" / "300-search.js",
    ROOT / "resources" / "viewer" / "places.html",
]
BEGIN = "// BEGIN combining-marks"
END = "// END combining-marks"
_BLOCK = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.DOTALL)
_VERSION = re.compile(r"Unicode (\d+\.\d+\.\d+)")
_HEX = re.compile(r"0x([0-9A-Fa-f]+)")
PAIRS_PER_LINE = 6


def combining_code_points() -> list[int]:
    """Every code point whose canonical combining class is not 0."""
    return [c for c in range(0x110000) if unicodedata.combining(chr(c))]


def ranges(cps: list[int]) -> list[tuple[int, int]]:
    out: list[list[int]] = []
    for c in cps:
        if out and out[-1][1] == c - 1:
            out[-1][1] = c
        else:
            out.append([c, c])
    return [(a, b) for a, b in out]


def render(version: str | None = None, cps: list[int] | None = None) -> str:
    version = version or unicodedata.unidata_version
    rs = ranges(cps if cps is not None else combining_code_points())
    body: list[str] = []
    for i in range(0, len(rs), PAIRS_PER_LINE):
        row = rs[i:i + PAIRS_PER_LINE]
        body.append("    " + " ".join(f"0x{a:04X}, 0x{b:04X}," for a, b in row))
    body[-1] = body[-1].rstrip(",")
    return "\n".join([
        f"{BEGIN} (generated by tools/gen_combining_marks.py; do not edit)",
        f"  // Unicode {version}: every code point whose canonical combining class",
        "  // is not 0, as [first, last] pairs -- what the writer's",
        "  // unicodedata.combining() drops.",
        "  var CCC_RANGES = [",
        *body,
        "  ];",
        f"  {END}",
    ])


def _vtuple(v: str) -> tuple[int, ...]:
    return tuple(int(x) for x in v.split("."))


def parse_block(block: str) -> tuple[str, set[int]]:
    """(Unicode version, code points) of a generated block."""
    m = _VERSION.search(block)
    if not m:
        raise ValueError("no 'Unicode X.Y.Z' line in the combining-marks block")
    nums = [int(h, 16) for h in _HEX.findall(block.split("CCC_RANGES", 1)[1])]
    if len(nums) % 2:
        raise ValueError("odd number of range bounds")
    cps: set[int] = set()
    for a, b in zip(nums[::2], nums[1::2]):
        cps.update(range(a, b + 1))
    return m.group(1), cps


def check_block(block: str, running: str | None = None,
                cps: list[int] | None = None) -> str | None:
    """None if ``block`` is current for this Python, else why not."""
    running = running or unicodedata.unidata_version
    have = set(cps if cps is not None else combining_code_points())
    recorded, table = parse_block(block)
    if _vtuple(running) > _vtuple(recorded):
        return (f"table is from Unicode {recorded}, this Python has {running}: "
                "regenerate with this Python")
    if running == recorded:
        if block != render(running, sorted(have)):
            return f"table differs from what Unicode {running} generates"
        return None
    missing = have - table
    if missing:
        return (f"Unicode {running} has combining marks the {recorded} table lacks: "
                + ", ".join(f"U+{c:04X}" for c in sorted(missing)[:10]))
    assigned = [c for c in table - have if unicodedata.category(chr(c)) != "Cn"]
    if assigned:
        return (f"the {recorded} table strips characters Unicode {running} assigns "
                "with class 0: " + ", ".join(f"U+{c:04X}" for c in assigned[:10]))
    return None


def _blocks(path: Path) -> list[str]:
    return _BLOCK.findall(path.read_text(encoding="utf-8"))


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=next(iter((__doc__ or "").splitlines()), ""))
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if a table is stale for this Python's Unicode version")
    ap.add_argument("--allow-older", action="store_true",
                    help="write the table even if this Python's Unicode is older than it")
    args = ap.parse_args(argv)
    running = unicodedata.unidata_version
    bad = 0
    for path in TARGETS:
        rel = path.relative_to(ROOT)
        blocks = _blocks(path)
        if len(blocks) != 1:
            print(f"{rel}: want exactly one combining-marks block, found {len(blocks)}",
                  file=sys.stderr)
            bad += 1
            continue
        if args.check:
            why = check_block(blocks[0], running)
            if why:
                print(f"{rel}: {why}.\nRun tools/gen_combining_marks.py with the newest "
                      "Python in use (3.14, e.g. in the Docker image), then "
                      "tools/build_viewer.py", file=sys.stderr)
                bad += 1
            else:
                recorded = parse_block(blocks[0])[0]
                how = "matches" if recorded == running else f"covers Unicode {running}"
                print(f"ok: {rel} combining-marks table (Unicode {recorded}) {how}")
            continue
        recorded = parse_block(blocks[0])[0]
        if _vtuple(running) < _vtuple(recorded) and not args.allow_older:
            print(f"{rel}: table is from Unicode {recorded}, this Python has only "
                  f"{running}; use a newer Python (or --allow-older)", file=sys.stderr)
            bad += 1
            continue
        text = path.read_text(encoding="utf-8")
        new = _BLOCK.sub(lambda _m: render(running), text)
        if new != text:
            path.write_text(new, encoding="utf-8")
            print(f"wrote {rel} (Unicode {running})")
        else:
            print(f"unchanged: {rel} (Unicode {running})")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
