#!/usr/bin/env python3
"""Generate streetzim/overture_taxonomy.py: Overture's place taxonomy mapped
back to the pre-2026-09-23 `categories` names.

    python3 tools/gen_taxonomy_legacy.py [--release 2026-08-19.0] [--out PATH]

Reads `categories.primary` and `taxonomy.primary` of every place in a release
that carries both columns (2026-08-19.0 is the last one), over anonymous
HTTPS. Only those two columns are fetched: about 4 minutes and a few hundred
MB of column chunks for 73.6 M places. Writes:
- TAXONOMY_TO_LEGACY: every taxonomy.primary whose most frequent
  categories.primary differs from it, sorted by key;
- LEGACY_NAMES: every distinct categories.primary;
- a comment naming the rows that do not pair one-to-one.

Needs duckdb with the httpfs extension, and network access to the
overturemaps-us-west-2 bucket.
"""
from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

import download_overture_data as dl  # noqa: E402

HEADER = '''"""Generated by tools/gen_taxonomy_legacy.py from Overture release {release}
({rows:,} places with a category). Do not edit; regenerate.

TAXONOMY_TO_LEGACY: taxonomy.primary -> categories.primary, for the
{n_map} names that differ. LEGACY_NAMES: the {n_legacy} distinct
categories.primary values, i.e. the vocabulary search records, chip rules
and the generic-bucket refinement use.

Rows that do not pair one-to-one (taxonomy.primary, categories.primary,
rows); the most frequent pairing wins:
{odd}
"""
from __future__ import annotations

'''


def pairs(release: str) -> list[tuple[str | None, str | None, int]]:
    import duckdb
    urls = [f"{dl.OVERTURE_HTTPS}/{k}" for k in dl.theme_files(release, "places")]
    if not urls:
        raise SystemExit(f"no places files for release {release}")
    con = duckdb.connect()
    con.execute("INSTALL httpfs; LOAD httpfs;")
    con.execute("SET http_retries=8; SET http_retry_backoff=2; SET http_retry_wait_ms=500;")
    print(f"scanning {len(urls)} files of {release}...", file=sys.stderr)
    return con.execute(
        "SELECT taxonomy.primary, categories.primary, count(*) "
        f"FROM read_parquet({urls!r}) GROUP BY ALL").fetchall()


def render(release: str, rows: list[tuple[str | None, str | None, int]]) -> str:
    by_tax: dict[str, dict[str, int]] = defaultdict(dict)
    legacy: set[str] = set()
    total = 0
    for tax, cat, n in rows:
        if cat:
            legacy.add(cat)
        if tax and cat:
            by_tax[tax][cat] = by_tax[tax].get(cat, 0) + n
            total += n
    mapping: dict[str, str] = {}
    odd: list[str] = []
    for tax, cats in sorted(by_tax.items()):
        best = max(sorted(cats), key=lambda c: cats[c])
        if best != tax:
            mapping[tax] = best
        for cat, n in sorted(cats.items()):
            if cat != best:
                odd.append(f"  {tax} -> {cat}: {n} (kept {best}: {cats[best]:,})")
    out = HEADER.format(release=release, rows=total, n_map=len(mapping),
                        n_legacy=len(legacy), odd="\n".join(odd) or "  none")
    out += "TAXONOMY_TO_LEGACY: dict[str, str] = {\n"
    out += "".join(f'    "{k}": "{v}",\n' for k, v in sorted(mapping.items()))
    out += "}\n\nLEGACY_NAMES: frozenset[str] = frozenset({\n"
    out += "".join(f'    "{c}",\n' for c in sorted(legacy))
    out += "})\n"
    return out


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--release", default="2026-08-19.0",
                   help="a release with both categories and taxonomy")
    p.add_argument("--out", default=str(ROOT / "streetzim" / "overture_taxonomy.py"))
    args = p.parse_args()
    Path(args.out).write_text(render(args.release, pairs(args.release)), encoding="utf-8")
    print(f"wrote {args.out}", file=sys.stderr)


if __name__ == "__main__":
    main()
